name: Update README and Push Changes

on:
  push:
    branches:
      - main  # Modify this to match your default branch name
    paths: 
      - 'docs/*'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          # Modify the README file using a command-line tool
          echo "This is a modified README file." > README.md

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add README.md
          git commit -m "Update README"
          git push https://${{ secrets.A_TOKEN }} HEAD:main
          # git push origin main  # Modify 'main' to match your default branch name
